import subprocess
import os
import glob

project_root = r"d:\LOOP_COMPANY\HyperClip"
downloads_dir = os.path.join(project_root, 'data', 'downloads')
downloaded_files = glob.glob(os.path.join(downloads_dir, "*.mp4"))

if not downloaded_files:
    print("No downloaded files found to test.")
    exit(1)

input_file = downloaded_files[0]
output_file = os.path.join(project_root, 'data', 'renders', 'test_cpu_part2.mp4')
if os.path.exists(output_file):
    os.remove(output_file)

# Recreate the exact filter string generated by build_landscape_filter
# for trim_start = 30.0, trim_duration = 30.0, speed = 1.2
# fps = 30, canvas_w = 1920, canvas_h = 1080, video_h = 900, video_top = 180
# Under the current Rust logic:
# speed_tag = "setpts=0.8333333333333334*PTS,"
# trim_tag = "trim=start=25:duration=25,setpts=PTS-STARTPTS,"
# reset_pts = ",setpts=PTS-STARTPTS"
# video_chain = "[0:v]{2}{1}fps={0}{3},{4}=-2:{5}{6},crop={7}:{8}:{9}:0[vid]"
# which evaluates to:
# "[0:v]setpts=0.8333333333333334*PTS,trim=start=25:duration=25,setpts=PTS-STARTPTS,fps=30,,setpts=PTS-STARTPTS,scale=-2:900,crop=1920:900:0:0[vid]"

filter_complex = (
    "[0:v]setpts=0.8333333333333334*PTS,trim=start=25:duration=25,setpts=PTS-STARTPTS,fps=30,scale=1920:-2:flags=bicubic,crop=1920:900:0:270[vid]; "
    "[1:v]loop=loop=-1:size=1:start=0,fps=30,scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080:(ow-iw)/2:(oh-ih)/2[bg]; "
    "[bg][vid]overlay=0:180 [vz]; "
    "[2:v]loop=loop=-1:size=1:start=0,scale=1920:216:force_original_aspect_ratio=increase,crop=1920:216:(ow-iw)/2:(oh-ih)/2,setsar=1,format=yuv420p[hd]; "
    "[vz][hd]overlay=0:0 [final]"
)

# Dummy lavfi colors for 1:v and 2:v
cmd = [
    'ffmpeg', '-hide_banner', '-y',
    '-i', input_file,
    '-f', 'lavfi', '-i', 'color=c=0x2d2d2d:s=1920x1080:d=25.0',
    '-f', 'lavfi', '-i', 'color=c=0x0d0d0d:s=1920x216:d=25.0',
    '-filter_complex', filter_complex,
    '-t', '25.0',
    '-map', '[final]',
    '-c:v', 'libx264', '-preset', 'ultrafast',
    output_file
]

print("Running FFmpeg command...")
res = subprocess.run(cmd, capture_output=True, text=True)
if res.returncode == 0:
    print("[SUCCESS] FFmpeg completed successfully!")
else:
    print("[FAIL] FFmpeg failed with exit code:", res.returncode)
    print("Error output:")
    print(res.stderr)
